/**
 * Central site configuration. All user-facing copy here is Lithuanian.
 * The base URL defaults to the canonical origin (see resolveSiteUrl).
 */

export interface NavItem {
  href: string;
  label: string;
}

/**
 * The origin Vercel actually serves. The apex `verslas.ai` 308-redirects here,
 * so canonical URLs, the sitemap and JSON-LD must use www.
 */
const CANONICAL_ORIGIN = 'https://www.verslas.ai';

/**
 * NEXT_PUBLIC_SITE_URL may override the origin (local dev, other hosts). It is
 * trimmed (a stray tab once leaked into production URLs) and the redirecting
 * apex is mapped to the canonical origin.
 */
function resolveSiteUrl(value: string | undefined): string {
  const trimmed = value?.trim();
  if (!trimmed) return CANONICAL_ORIGIN;
  const url = new URL(trimmed);
  if (url.hostname === 'verslas.ai') return CANONICAL_ORIGIN;
  return url.origin;
}

export const siteConfig = {
  name: 'verslas.ai',
  url: resolveSiteUrl(process.env.NEXT_PUBLIC_SITE_URL),
  /** One-line brand promise used on the home hero. */
  tagline: 'Dirbtinis intelektas tavo verslui — be teorijos, su pavyzdžiais.',
  /** Default meta description (Lithuanian). */
  description:
    'Konkretūs, pavyzdžiais paremti straipsniai apie tai, kaip naudoti dirbtinį intelektą versle. Realūs scenarijai, žingsnis po žingsnio ir paruošti promptai.',
  locale: 'lt_LT',
  lang: 'lt',
  /**
   * Where order/contact submissions go. Override on Vercel with
   * NEXT_PUBLIC_CONTACT_EMAIL; the branded fallback can be set up as a
   * forwarding address on the domain.
   */
  contactEmail: process.env.NEXT_PUBLIC_CONTACT_EMAIL?.trim() || 'labas@verslas.ai',
  nav: [
    { href: '/', label: 'Pradžia' },
    { href: '/reklaminis-video', label: 'Video' },
    { href: '/straipsniai', label: 'Straipsniai' },
    { href: '/kursai', label: 'Kursai' },
    { href: '/apie', label: 'Apie' },
  ] satisfies NavItem[],
  /** Default values for the reusable <CTA /> funnel component. */
  cta: {
    eyebrow: 'Reklaminis video',
    title: 'Reklaminis video tavo verslui — 99 €',
    description:
      'Trumpas, reklamai paruoštas klipas per 4 darbo dienas. Parodyk produktą ten, kur klientai jau žiūri — „Instagram“, „TikTok“ ir „Facebook“.',
    label: 'Užsisakyk video',
    href: '/reklaminis-video',
  },
  author: {
    name: 'verslas.ai komanda',
  },
  /** Legal entity behind the brand (JSON-LD publisher). */
  publisher: {
    legalName: 'MB AIverslui',
    /** Square PNG generated by app/logo.png/route.tsx. */
    logo: '/logo.png',
  },
  /**
   * robots.txt policy for AI *training* crawlers (GPTBot, ClaudeBot,
   * Google-Extended, Applebot-Extended, CCBot). Search/answer bots are always
   * allowed. Owner decision; default allow for AI visibility.
   */
  allowAiTrainingBots: true,
  social: {
    twitter: '@verslasai',
  },
} as const;

export type SiteConfig = typeof siteConfig;
