import type { Author } from './authors';
import { lastModified, type Post } from './posts';
import { siteConfig } from './site';

/**
 * Schema.org JSON-LD builders. Pure functions so the output is easy to test
 * and every page emits the same entity shapes.
 */

type JsonLdNode = Record<string, unknown>;

const ORGANIZATION_ID = `${siteConfig.url}/#organization`;
const WEBSITE_ID = `${siteConfig.url}/#website`;
const LANGUAGE = 'lt-LT';

export function absoluteUrl(path: string): string {
  return path.startsWith('http') ? path : `${siteConfig.url}${path}`;
}

export function articleUrl(slug: string): string {
  return absoluteUrl(`/straipsniai/${slug}`);
}

export function organizationNode(): JsonLdNode {
  return {
    '@type': 'Organization',
    '@id': ORGANIZATION_ID,
    name: siteConfig.name,
    legalName: siteConfig.publisher.legalName,
    url: siteConfig.url,
    logo: {
      '@type': 'ImageObject',
      url: absoluteUrl(siteConfig.publisher.logo),
      width: 512,
      height: 512,
    },
  };
}

function websiteNode(): JsonLdNode {
  return {
    '@type': 'WebSite',
    '@id': WEBSITE_ID,
    name: siteConfig.name,
    url: siteConfig.url,
    description: siteConfig.description,
    inLanguage: LANGUAGE,
    publisher: { '@id': ORGANIZATION_ID },
  };
}

function personNode(author: Author): JsonLdNode {
  return {
    '@type': 'Person',
    name: author.name,
    ...(author.url ? { url: absoluteUrl(author.url) } : {}),
    ...(author.jobTitle ? { jobTitle: author.jobTitle } : {}),
    ...(author.sameAs.length > 0 ? { sameAs: author.sameAs } : {}),
  };
}

/** Home page graph: the publishing organization and the website itself. */
export function siteJsonLd(): JsonLdNode {
  return {
    '@context': 'https://schema.org',
    '@graph': [organizationNode(), websiteNode()],
  };
}

export function breadcrumbNode(
  items: { name: string; path: string }[],
): JsonLdNode {
  return {
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: item.name,
      item: absoluteUrl(item.path),
    })),
  };
}

/**
 * Article page graph: BlogPosting (NewsArticle for `type: news`), breadcrumbs
 * and — only when the page shows a visible FAQ — FAQPage.
 */
export function articleJsonLd(post: Post, author: Author | undefined): JsonLdNode {
  const url = articleUrl(post.slug);

  const article: JsonLdNode = {
    '@type': post.type === 'news' ? 'NewsArticle' : 'BlogPosting',
    '@id': `${url}#article`,
    headline: post.title,
    description: post.excerpt,
    // Raster 1200×630 card generated by the route's opengraph-image.tsx.
    image: [absoluteUrl(`/straipsniai/${post.slug}/opengraph-image`)],
    datePublished: post.date,
    dateModified: lastModified(post),
    inLanguage: LANGUAGE,
    author: author
      ? personNode(author)
      : { '@type': 'Organization', name: siteConfig.author.name, url: siteConfig.url },
    publisher: organizationNode(),
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
    isPartOf: { '@id': WEBSITE_ID },
  };

  if (post.tags.length > 0) {
    article.keywords = post.tags.join(', ');
  }
  if (post.entities.length > 0) {
    article.mentions = post.entities.map((entity) => ({
      '@type': 'Thing',
      name: entity.name,
      ...(entity.sameAs.length > 0 ? { sameAs: entity.sameAs } : {}),
    }));
  }
  if (post.sources.length > 0) {
    article.citation = post.sources.map((source) => ({
      '@type': 'CreativeWork',
      name: source.title,
      url: source.url,
      ...(source.publisher
        ? { publisher: { '@type': 'Organization', name: source.publisher } }
        : {}),
      ...(source.date ? { datePublished: source.date } : {}),
    }));
  }

  const graph: JsonLdNode[] = [
    article,
    breadcrumbNode([
      { name: 'Pradžia', path: '/' },
      { name: 'Straipsniai', path: '/straipsniai' },
      { name: post.title, path: `/straipsniai/${post.slug}` },
    ]),
  ];

  if (post.faq.length > 0) {
    graph.push({
      '@type': 'FAQPage',
      mainEntity: post.faq.map((item) => ({
        '@type': 'Question',
        name: item.q,
        acceptedAnswer: { '@type': 'Answer', text: item.a },
      })),
    });
  }

  return { '@context': 'https://schema.org', '@graph': graph };
}
